print("ingrese su primer nombre")
p =input()
print("ingrese su segundo nombre")
s=input()
print("ingrese su primer apellido")
a=input()
print("ingrese su segundo apellido")
b=input()
print("ingrese su edad")
e=input()
print("ingrese su año de nacimiento")
n=input()
print("nombre completo: " + p + "" + s + "" + a + "" + b)
print("edad: " + e)
print("año de nacimiento:" + n)